"""Added cascade delete on blogs

Revision ID: 429cd89a6bcf
Revises: c0ed2417e541
Create Date: 2025-10-31 14:01:08.682459

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '429cd89a6bcf'
down_revision: Union[str, Sequence[str], None] = 'c0ed2417e541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blogs_user_id_fkey'), 'blogs', type_='foreignkey')
    op.create_foreign_key(None, 'blogs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'blogs', type_='foreignkey')
    op.create_foreign_key(op.f('blogs_user_id_fkey'), 'blogs', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
